query transactionsByUser($email: String!){
  userByEmail(email: $email) {
    transactions(_size: 1000) {
      data {
        _id
        title
        price
        pay
        dueDate
        category {
          _id,
          name
        }
        type {
          _id
          name
        }
      }
    }
  }
}